# ./docker/php/Dockerfile
FROM php:7.2-fpm

RUN docker-php-ext-install pdo_mysql

RUN pecl install apcu

RUN apt-get update && \
apt-get install -y \
zlib1g-dev git

RUN docker-php-ext-install zip
RUN docker-php-ext-enable apcu

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --filename=composer \
    && php -r "unlink('composer-setup.php');" \
    && mv composer /usr/local/bin/composer

RUN mkdir -p -m 777 /.symfony
RUN mkdir -p -m 777 /.composer

WORKDIR /usr/src/app

COPY app /usr/src/app

RUN PATH=$PATH:/usr/src/apps/vendor/bin:bin
