version: '3.7'
services:
    mysql:
      container_name: mysql
      image: mysql:8
      command: --default-authentication-plugin=mysql_native_password
      restart: on-failure
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}

    php:
       container_name: php
       build:
         context: .
         dockerfile: docker/php/Dockerfile
       restart: on-failure
       volumes:
         - './app/:/usr/src/app'
       user: ${LOCAL_USER}  

    nginx:
       container_name: nginx
       image: nginx:1.15.3-alpine
       restart: on-failure
       volumes:
         - './app/public/:/usr/src/app'
         - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
       ports:
         - '${NGINX_PORT}:80'    
       depends_on:
         - php

    mongo:
      container_name: mongo
      image: mongo
      restart: on-failure
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      ports:
         - '${MONGO_PORT}:27017'

    adminer:
       container_name: adminer
       image: adminer
       environment:
         - ADMINER_DESIGN:'nette'
       restart: on-failure
       ports:
         - '${ADMINER_PORT}:8080'

    portainer:
       container_name: portainer
       image: portainer/portainer
       restart: on-failure
       ports:
         - '${PORTAINER_PORT}:9000'

    rabbit:
      container_name: rabbit
      image: rabbitmq
      environment:
        - RABBITMQ_NODE_TYPE=rabbit
        - RABBITMQ_NODE_NAME=rabbit@rabbit
        - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      ports:
        - '${RABBIT_PORT}:15672'
